apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: my-python-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1           # max 1 Pod niedostępny podczas aktualizacji
      maxSurge: 1                 # max 1 dodatkowy Pod podczas aktualizacji
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask
          image: my-registry/flask-app:1.0.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
